// import '../styles/globals.css'
// import { Inter } from 'next/font/google'
import ThemeRegistry from './themeRegistry';
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeRegistry options={{ key: 'mui-theme' }}>{children}</ThemeRegistry>
            </body>
        </html>
    );
}

// import '../styles/globals.css';
// import { Footer } from '../components/footer';
// import { Header } from '../components/header';

// export const metadata = {
//     title: {
//         template: '%s | Netlify',
//         default: 'Netlify Starter'
//     }
// };

// export default function RootLayout({ children }) {
//     return (
//         <html lang="en" suppressHydrationWarning>
//             <head>
//                 <link rel="icon" href="/favicon.svg" sizes="any" />
//             </head>
//             <body className="antialiased text-white bg-blue-900">
//                 <div className="flex flex-col min-h-screen px-6 bg-noise sm:px-12">
//                     <div className="flex flex-col w-full max-w-5xl mx-auto grow">
//                         <Header />
//                         <main className="grow">{children}</main>
//                         <Footer />
//                     </div>
//                 </div>
//             </body>
//         </html>
//     );
// }
